//! Generates the per-host builtin metadata tables from `builtins.ron`.
//!
//! The RON file is the one place a builtin's name, signature, and doc line
//! live. This script reads it once at compile time and writes plain
//! `&'static [BuiltinFn]` slices into `OUT_DIR`, which
//! `lumen_script::builtins` includes. The parser is a build dependency, so
//! nothing ships in the runtime and nothing is parsed when an app runs.
//!
//! Adding a host means adding a `Host` variant here and a table below.

use std::collections::HashSet;
use std::path::Path;

use serde::Deserialize;

/// A script host that can expose a builtin.
#[derive(Deserialize, Clone, Copy, PartialEq, Eq, Hash, Debug)]
enum Host {
    Rhai,
    Lua,
    Candela,
}

impl Host {
    /// Name of the generated table for this host.
    fn table(self) -> &'static str {
        match self {
            Host::Rhai => "RHAI_BUILTINS",
            Host::Lua => "LUA_BUILTINS",
            Host::Candela => "CANDELA_BUILTINS",
        }
    }

    /// Human-readable host name for the generated doc comment.
    fn label(self) -> &'static str {
        match self {
            Host::Rhai => "Rhai",
            Host::Lua => "Lua",
            Host::Candela => "candela",
        }
    }
}

/// A per-host replacement for the fields an entry spells differently there.
/// An omitted field keeps the entry's shared value.
#[derive(Deserialize)]
struct Override {
    host: Host,
    #[serde(default)]
    params: Option<Vec<(String, String)>>,
    #[serde(default)]
    ret: Option<String>,
    #[serde(default)]
    doc: Option<String>,
}

/// One builtin, with the hosts that expose it.
#[derive(Deserialize)]
struct Builtin {
    name: String,
    hosts: Vec<Host>,
    params: Vec<(String, String)>,
    ret: String,
    doc: String,
    #[serde(default)]
    overrides: Vec<Override>,
}

#[derive(Deserialize)]
struct Table {
    builtins: Vec<Builtin>,
}

fn main() {
    let dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let ron_path = Path::new(&dir).join("builtins.ron");
    println!("cargo:rerun-if-changed={}", ron_path.display());

    let src = std::fs::read_to_string(&ron_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", ron_path.display()));
    let table: Table = ron::from_str(&src)
        .unwrap_or_else(|e| panic!("{} is not valid builtin metadata: {e}", ron_path.display()));

    validate(&table, &ron_path);

    let mut out = String::from(
        "// Generated by build.rs from builtins.ron. Edit that file, not this one.\n\n",
    );
    for host in [Host::Rhai, Host::Lua, Host::Candela] {
        out.push_str(&render(&table, host));
    }

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("builtins_table.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

/// Reject metadata that would generate a table no test could make sense of:
/// a duplicate name, an entry no host exposes, or an override for a host the
/// entry does not list.
fn validate(table: &Table, path: &Path) {
    let mut seen = HashSet::new();
    for b in &table.builtins {
        assert!(
            seen.insert(b.name.as_str()),
            "{}: duplicate builtin `{}`",
            path.display(),
            b.name
        );
        assert!(
            !b.hosts.is_empty(),
            "{}: builtin `{}` lists no hosts",
            path.display(),
            b.name
        );
        for o in &b.overrides {
            assert!(
                b.hosts.contains(&o.host),
                "{}: builtin `{}` overrides {:?}, which it does not list as a host",
                path.display(),
                b.name,
                o.host
            );
        }
    }
}

/// Render one host's table: every entry that names the host, with its
/// overrides applied.
fn render(table: &Table, host: Host) -> String {
    let mut out = format!(
        "/// Every builtin the {} host exposes, generated from `builtins.ron`.\n\
         pub const {}: &[BuiltinFn] = &[\n",
        host.label(),
        host.table()
    );
    for b in table.builtins.iter().filter(|b| b.hosts.contains(&host)) {
        let o = b.overrides.iter().find(|o| o.host == host);
        let params = o.and_then(|o| o.params.as_ref()).unwrap_or(&b.params);
        let ret = o.and_then(|o| o.ret.as_deref()).unwrap_or(&b.ret);
        let doc = o.and_then(|o| o.doc.as_deref()).unwrap_or(&b.doc);

        out.push_str("    BuiltinFn {\n");
        out.push_str(&format!("        name: {},\n", quote(&b.name)));
        if params.is_empty() {
            out.push_str("        params: &[],\n");
        } else {
            out.push_str("        params: &[\n");
            for (name, ty) in params {
                out.push_str(&format!(
                    "            BuiltinParam {{ name: {}, ty: {} }},\n",
                    quote(name),
                    quote(ty)
                ));
            }
            out.push_str("        ],\n");
        }
        out.push_str(&format!("        ret: {},\n", quote(ret)));
        out.push_str(&format!("        doc: {},\n", quote(doc)));
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    out
}

/// Render `s` as a Rust string literal.
fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}
