[package]
name = "lumen-async-tokio"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "tokio Spawn + Timer impl."

[dependencies]
lumen-core = { path = "../core" }
bevy_ecs.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time", "fs", "net"] }
crossbeam-channel.workspace = true
tracing.workspace = true
