//! Drives the built fixture cdylib through `PluginSet`, hook by hook.

use std::path::{Path, PathBuf};

use lumenc_plugin::lumen_ir::layout_ir::LayoutIR;
use lumenc_plugin::{PluginCfg, PluginError, PluginSet, SourceKind, testing};

fn cfg(name: &str, path: &Path, config: &str) -> PluginCfg {
    let doc: toml::Table = toml::from_str(&format!(
        "[[plugins]]\nname = \"{name}\"\npath = '{}'\n[plugins.config]\n{config}\n",
        path.display()
    ))
    .unwrap();
    PluginCfg::from_document(&doc).unwrap().remove(0)
}

fn load(app_dir: &Path, config: &str) -> PluginSet {
    let lib = testing::fixture_cdylib();
    PluginSet::load(app_dir, &[cfg("lumen-plugin-fixture", &lib, config)]).unwrap()
}

fn temp_dir(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("lumenc-plugin-roundtrip-{tag}"));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn markup_and_css_transform() {
    let dir = temp_dir("source");
    let set = load(&dir, "");
    let entry = dir.join("main.lmn");
    let out = set
        .transform_source(
            SourceKind::Markup,
            "<root><label text=\"FROM_PLUGIN_MARKUP\"/></root>".to_string(),
            &entry,
            &entry,
        )
        .unwrap();
    assert!(out.contains("markup-transformed"), "{out}");

    let css = set
        .transform_source(
            SourceKind::Css,
            ".x { color: PLUGIN_COLOR; }".to_string(),
            &entry,
            &entry,
        )
        .unwrap();
    assert_eq!(css, ".x { color: rgb(255, 0, 0); }");

    // No marker: the hook reports UNCHANGED and the text passes through.
    let same = set
        .transform_source(SourceKind::Markup, "<root/>".to_string(), &entry, &entry)
        .unwrap();
    assert_eq!(same, "<root/>");
}

#[test]
fn ir_transform_injects() {
    let dir = temp_dir("ir");
    let set = load(&dir, "inject_text = \"hello\"");
    let mut ir = LayoutIR::default();
    set.transform_ir(&mut ir, &dir.join("main.lmn")).unwrap();
    let child = ir.root.children.last().expect("injected child");
    assert_eq!(child.tag, "label");
    assert_eq!(child.attrs.text.as_deref(), Some("hello"));
    assert_eq!(child.attrs.classes, ["from-plugin"]);
}

#[test]
fn lint_and_emit() {
    let dir = temp_dir("finish");
    let set = load(
        &dir,
        "lint_message = \"from lint\"\nemit_path = \"out/report.txt\"",
    );
    let ir = LayoutIR::default();
    let findings = set.finish(&ir, &dir.join("main.lmn")).unwrap();
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0].0, "lumen-plugin-fixture");
    assert_eq!(findings[0].1.message, "from lint");
    let written = dir.join(".lumen/generated/lumen-plugin-fixture/out/report.txt");
    assert_eq!(std::fs::read(&written).unwrap(), b"generated by fixture");

    let rendered = PluginSet::render_findings(&findings, &dir.join("main.lmn"));
    assert!(
        rendered[0].contains("[lumen-plugin-fixture/fixture]"),
        "{}",
        rendered[0]
    );
    assert!(rendered[0].starts_with("info"), "{}", rendered[0]);
}

#[test]
fn check_only_discards_emit() {
    let dir = temp_dir("check");
    let set = load(&dir, "emit_path = \"report.txt\"").check_only(true);
    set.finish(&LayoutIR::default(), &dir.join("main.lmn"))
        .unwrap();
    assert!(!dir.join(".lumen").exists());
}

#[test]
fn hook_error_names_plugin_and_hook() {
    let dir = temp_dir("err");
    let set = load(&dir, "fail = \"ir\"");
    let err = set
        .transform_ir(&mut LayoutIR::default(), &dir.join("main.lmn"))
        .unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("plugin 'lumen-plugin-fixture'"), "{msg}");
    assert!(msg.contains("transform_ir failed"), "{msg}");
    assert!(msg.contains("fixture failure in ir"), "{msg}");
}

#[test]
fn hook_panic_is_an_error_not_an_abort() {
    let dir = temp_dir("panic");
    let set = load(&dir, "panic_in = \"lint\"");
    let err = set
        .finish(&LayoutIR::default(), &dir.join("main.lmn"))
        .unwrap_err();
    assert!(matches!(err, PluginError::Panicked { .. }), "{err}");
    assert!(err.to_string().contains("fixture panic in lint"), "{}", err);
}

#[test]
fn bad_emit_path_is_refused() {
    let dir = temp_dir("badpath");
    let set = load(&dir, "emit_bad_path = \"../escape.txt\"");
    let err = set
        .finish(&LayoutIR::default(), &dir.join("main.lmn"))
        .unwrap_err();
    assert!(matches!(err, PluginError::BadOutput { .. }), "{err}");
}

#[test]
fn name_mismatch_is_refused_at_load() {
    let dir = temp_dir("name");
    let lib = testing::fixture_cdylib();
    let err = PluginSet::load(&dir, &[cfg("wrong-name", &lib, "")]).unwrap_err();
    assert!(matches!(err, PluginError::NameMismatch { .. }), "{err}");
}

#[test]
fn missing_file_reports_probed_paths() {
    let dir = temp_dir("missing");
    let doc: toml::Table =
        toml::from_str("[[plugins]]\nname = \"ghost\"\npath = \"plugins/ghost\"\n").unwrap();
    let cfgs = PluginCfg::from_document(&doc).unwrap();
    let err = PluginSet::load(&dir, &cfgs).unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("libghost.so"), "{msg}");
    assert!(msg.contains("libghost.dylib"), "{msg}");
    assert!(msg.contains("ghost.dll"), "{msg}");
}

#[test]
fn declaration_order_composes() {
    let dir = temp_dir("order");
    let lib = testing::fixture_cdylib();
    let set = PluginSet::load(
        &dir,
        &[
            cfg("lumen-plugin-fixture", &lib, "order = \"a\""),
            cfg("lumen-plugin-fixture", &lib, "order = \"b\""),
            cfg("lumen-plugin-fixture", &lib, "order = \"c\""),
        ],
    )
    .unwrap();
    let entry = dir.join("main.lmn");
    let out = set
        .transform_source(
            SourceKind::Markup,
            "<root>/END</root>".to_string(),
            &entry,
            &entry,
        )
        .unwrap();
    assert_eq!(out, "<root>abc/END</root>");
}
