/*
 * Lumen C ABI.
 *
 * Mostly hand-written. The complex tagged-union (LumenValue,
 * LumenValueData, LumenArrayView, LumenMapView, LumenMapEntry, LumenFn)
 * lives here because cbindgen stumbles on the recursive value cycle
 * and on Option<extern "C" fn>. The simple-side surface (status enum,
 * lifecycle entry points, signal mutators, ABI version) is generated
 * by cbindgen into `lumen_simple.h`, which this file #includes.
 *
 * Threading: every `lumen_*` function is safe to call from any
 * thread. `LumenFn` callbacks fire on the Lumen script thread.
 *
 * Ownership: pointers passed in/out of `LumenFn` (string, array,
 * map) are borrowed for the duration of the call. Lumen copies
 * immediately; the embedder is free to reuse / free buffers as
 * soon as the call returns.
 *
 * user_data contract: the opaque pointer passed to `lumen_app_expose`
 * is stored verbatim and passed back to the embedder's callback. Lumen
 * never dereferences it. The embedder is responsible for ensuring the
 * referent stays alive AND is safe to read from the Lumen script
 * thread (which may not be the embedder's main thread). This matches
 * Qt5/6's `void* user_data` and GLib's `gpointer user_data` contracts.
 *
 * Errors: every function returns `LumenStatus` (or `NULL` for
 * constructors). On non-OK status, `lumen_last_error()` returns a
 * thread-local NUL-terminated UTF-8 message. When the thread-local
 * slot is empty, the global last-error slot is consulted instead, so
 * an embedder that writes the error on thread A and checks it on
 * thread B still gets a useful message.
 *
 * ABI versioning: `LUMEN_API_VERSION` is the header's view of the
 * ABI; `lumen_abi_version()` returns the linked library's view. Compare
 * at startup and refuse mismatches in the major/minor pair.
 */

#ifndef LUMEN_H
#define LUMEN_H

#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations needed by lumen_simple.h. The opaque LumenApp
 * handle is referenced by the generated lifecycle exports below. The
 * LumenStatus enum is defined here (rather than via cbindgen) so the
 * C identifiers LUMEN_OK / LUMEN_ERR_* keep their historical spelling. */
typedef struct LumenApp LumenApp;

/* ============================================================
 * ABI version
 * ============================================================ */

/*
 * Packed ABI version this header was written against:
 *   (major << 16) | (minor << 8) | patch
 *
 * Compare against `lumen_abi_version()` at startup. A mismatch in the
 * top 24 bits (major+minor) is a hard incompatibility.
 */
#define LUMEN_API_VERSION_MAJOR 0u
#define LUMEN_API_VERSION_MINOR 12u
#define LUMEN_API_VERSION_PATCH 0u
#define LUMEN_API_VERSION                                                          \
    ((LUMEN_API_VERSION_MAJOR << 16) | (LUMEN_API_VERSION_MINOR << 8) |            \
     LUMEN_API_VERSION_PATCH)

/* Forward declarations - break the LumenValue <-> container cycle.
 * LumenApp is forward-declared above so lumen_simple.h sees it. */
typedef struct LumenValue    LumenValue;
typedef struct LumenMapEntry LumenMapEntry;

/* ============================================================
 * LumenStatus - return code for every lumen_* C function.
 *
 * Hand-written so the C identifiers (LUMEN_OK, LUMEN_ERR_*) match
 * historical embedder code and lumen.hpp. The Rust `#[repr(u32)]`
 * source-of-truth lives in lumen-ffi/src/lib.rs::LumenStatus.
 * Numeric values are stable; W6.12 only appended new variants.
 * ============================================================ */
typedef enum LumenStatus {
    LUMEN_OK                 = 0,
    LUMEN_ERR_BAD_PATH       = 1,
    LUMEN_ERR_BAD_ARG        = 2,
    LUMEN_ERR_RUNTIME        = 3,
    LUMEN_ERR_INTERNAL       = 4,
    LUMEN_ERR_PARSE          = 5,
    LUMEN_ERR_CSS            = 6,
    LUMEN_ERR_ASSET          = 7,
    LUMEN_ERR_WINDOW         = 8,
    LUMEN_ERR_SCRIPT         = 9,
    LUMEN_ERR_IO             = 10,
    LUMEN_ERR_INVALID_HANDLE = 11,
    LUMEN_ERR_INVALID_VALUE  = 12,
    LUMEN_ERR_PANIC          = 13,
    /* A caller-provided output buffer was too small. Where the export
     * takes an `out_len`, it is set to the required capacity (bytes
     * needed, including the trailing NUL). Added in ABI 0.3. */
    LUMEN_ERR_BUFFER_TOO_SMALL = 14,
} LumenStatus;

/* Simple-side declarations generated by cbindgen. Brings in
 * lumen_abi_version() + the lifecycle / signal entry points. The
 * status enum stays hand-written above; cbindgen excludes it. */
#include "lumen_simple.h"

/* Discriminant for LumenValue. */
typedef enum LumenKind {
    LUMEN_NIL    = 0,
    LUMEN_BOOL   = 1,
    LUMEN_INT    = 2,
    LUMEN_FLOAT  = 3,
    LUMEN_STRING = 4,
    LUMEN_ARRAY  = 5,
    LUMEN_MAP    = 6,
} LumenKind;

/* Borrowed view of an array of LumenValue. */
typedef struct LumenArrayView {
    const LumenValue* items;
    size_t            len;
} LumenArrayView;

/* Borrowed view of a map of LumenMapEntry. */
typedef struct LumenMapView {
    const LumenMapEntry* entries;
    size_t               len;
} LumenMapView;

/* Payload union. Read the field matching LumenValue::kind. */
typedef union LumenValueData {
    int             boolean;     /* LUMEN_BOOL  (0 = false, !=0 = true) */
    int64_t         integer;     /* LUMEN_INT   */
    double          float_;      /* LUMEN_FLOAT */
    const char*     string;      /* LUMEN_STRING (UTF-8, NUL-terminated) */
    LumenArrayView  array;       /* LUMEN_ARRAY */
    LumenMapView    map;         /* LUMEN_MAP   */
} LumenValueData;

/* Tagged value. */
struct LumenValue {
    LumenKind       kind;
    LumenValueData  as_;
};

/* One entry in a LumenMapView. */
struct LumenMapEntry {
    const char* key;
    LumenValue  value;
};

/*
 * Signature of an exposed callback. `argv` is borrowed for the
 * duration of the call; the returned LumenValue must stay valid
 * until this function returns.
 */
typedef LumenValue (*LumenFn)(int argc,
                              const LumenValue* argv,
                              void* user_data);

/*
 * Out-parameter callback variant of LumenFn (ABI 0.3).
 *
 * Writes its result through `out` instead of returning a LumenValue by
 * value. Because LumenValue (24 bytes) exceeds the SysV x86-64 16-byte
 * register-pair return threshold, a by-value return forces every
 * non-Rust binding to hand-encode the platform's aggregate-return
 * (`sret`) convention; this variant sidesteps that entirely. `out` is
 * never NULL and points to a single writable LumenValue that Lumen has
 * zero-initialised to LUMEN_NIL - a callback returning nil may leave it
 * untouched. Any pointers the written value carries must stay valid
 * until the callback returns. Register with lumen_app_expose_v2().
 */
typedef void (*LumenFnV2)(LumenValue* out,
                          int argc,
                          const LumenValue* argv,
                          void* user_data);

/*
 * Id-scoped native click callback (ABI 0.3). Registered with
 * lumen_app_on_click(); Lumen calls it once per click on the element
 * whose id equals the registered id. `id` (UTF-8, NUL-terminated) is
 * borrowed for the call. Fires on the Lumen tick thread.
 */
typedef void (*LumenClickFn)(const char* id, void* user_data);

/*
 * Signal-change subscription callback (ABI 0.4). Registered with
 * lumen_signal_watch(); Lumen calls it once per tick in which the watched
 * global signal's committed value changed (and once on the first tick the
 * value is observed after registration). `name` (UTF-8, NUL-terminated) is
 * the watched signal name; `value` points to the new committed value,
 * borrowed for the duration of the call.
 *
 * The LumenValue mirrors the stored value: bool -> LUMEN_BOOL, int64 ->
 * LUMEN_INT, double -> LUMEN_FLOAT, string -> LUMEN_STRING, and color ->
 * LUMEN_INT packed big-endian 0xRRGGBBAA (unpack with (v>>24)&0xff ...
 * v&0xff). Other stored kinds arrive as LUMEN_NIL. Fires on the Lumen tick
 * thread; delivery is per-tick coalesced.
 */
typedef void (*LumenWatchFn)(const char* name, const LumenValue* value,
                             void* user_data);

/*
 * App-level close callback (ABI 0.5). Registered with
 * lumen_app_on_close(); Lumen calls it once per OS close request - the
 * window close button, or (Unix) the first SIGINT/SIGTERM - BEFORE the
 * runtime tears down the window, GPU state, or script host. Return
 * nonzero to allow the close (lumen_app_run() then returns), or 0 to
 * veto it and keep the window open (the hook fires again on the next
 * close request). On Unix a second SIGINT/SIGTERM bypasses the hook and
 * exits the process immediately, so a vetoing embedder cannot wedge
 * shutdown. Fires on the Lumen tick thread.
 */
typedef int (*LumenCloseFn)(void* user_data);

/* ============================================================
 * App lifecycle
 * ============================================================
 *
 * lumen_app_new / lumen_app_set_title / lumen_app_set_size /
 * lumen_app_free / lumen_app_run / lumen_last_error /
 * lumen_signal_set_string / lumen_signal_set_int /
 * lumen_signal_set_f64 / lumen_signal_clear / lumen_abi_version
 * are declared in `lumen_simple.h`.
 */

/*
 * Expose a native callback to Rhai under `name`. `arg_count` is the
 * arity (0..=8 sensible). `user_data` is stored by value; the
 * embedder owns it and must keep it valid until `lumen_app_run`
 * returns.
 */
LumenStatus lumen_app_expose(LumenApp* app,
                             const char* name,
                             uint32_t arg_count,
                             LumenFn func,
                             void* user_data);

/*
 * Out-parameter callback registration (ABI 0.3). Identical to
 * lumen_app_expose() except `func` is a LumenFnV2 that writes its result
 * through an out-pointer instead of returning a LumenValue by value.
 * Prefer this for ctypes / libffi-only bindings that cannot easily
 * express an aggregate (`sret`) return. lumen_app_expose() (v1) is
 * retained for source compatibility.
 */
LumenStatus lumen_app_expose_v2(LumenApp* app,
                                const char* name,
                                uint32_t arg_count,
                                LumenFnV2 func,
                                void* user_data);

/*
 * Register an id-scoped native click handler (ABI 0.3). `cb` fires once
 * per click on the element whose id equals `id`, routed by the runtime;
 * no main.lmn forwarding boilerplate, no per-embedder dispatch table
 * over the global on_click(id) hook. A second registration for the same
 * id REPLACES the first. Call before lumen_app_run(); coexists with any
 * script-side on_click(id). Native routing does not fire under
 * lumen_app_run_headless() (no input is injected there).
 */
LumenStatus lumen_app_on_click(LumenApp* app,
                               const char* id,
                               LumenClickFn cb,
                               void* user_data);

/*
 * Register an app-level close hook (ABI 0.5). `cb` fires once per OS
 * close request (window close button; Unix first SIGINT/SIGTERM) before
 * any teardown, and may veto the close by returning 0 - the native
 * counterpart of the script-side on_close() returning false; both
 * coexist and either may veto. A second registration REPLACES the
 * first. Call before lumen_app_run(). The hook never fires under
 * lumen_app_run_headless() (no window, no OS close request).
 */
LumenStatus lumen_app_on_close(LumenApp* app,
                               LumenCloseFn cb,
                               void* user_data);

/*
 * Subscribe to changes of the global signal `name` (ABI 0.4). `cb` fires
 * on the Lumen tick thread once per tick in which `name`'s committed value
 * changed - and once on the first tick the value is observed after
 * registration, so a fresh watcher immediately learns the current state.
 *
 * This is a real commit-fired subscription wired through the running app's
 * PropertyStore dirty machinery, NOT a background polling loop; it only
 * fires while the app runs (lumen_app_run / lumen_app_run_headless).
 * Registration is global and independent of any LumenApp handle, callable
 * before or after the app is built, from any thread. A second
 * lumen_signal_watch for the same `name` ADDS another watcher (it does not
 * replace). Returns LUMEN_ERR_BAD_ARG when `cb` or `name` is null / `name`
 * is non-UTF-8.
 */
LumenStatus lumen_signal_watch(const char* name,
                               LumenWatchFn cb,
                               void* user_data);

/*
 * Consume the handle and drive `ticks` main-schedule ticks WITHOUT
 * opening a window or GPU surface (ABI 0.3). Builds the full app (same
 * plugin stack, scripts, reactive bindings as lumen_app_run) and calls
 * the internal tick loop `ticks` times. Signal round-trips, script
 * execution, <for>/<if> reconciliation and typed-property draining all
 * run; there is no windowing, input, or GPU rendering. `ticks = 0`
 * builds-and-drops (validates the app loads). After this returns, `app`
 * is freed - do not call lumen_app_free on the same pointer.
 */
LumenStatus lumen_app_run_headless(LumenApp* app, uint32_t ticks);

/*
 * Replace the contents of an array signal. `value->kind` must be
 * LUMEN_ARRAY; each item should be LUMEN_MAP whose entries become
 * one row of the bound `<for>` block. Non-string entries are
 * stringified before insertion.
 */
LumenStatus lumen_signal_set_array (const char* name, const LumenValue* value);

/* ============================================================
 * Typed scalar signal accessors (W7.x).
 *
 * Avoid the round-trip stringification of the legacy
 * `lumen_signal_set_int` / `lumen_signal_set_f64` exports. Each setter
 * lands a typed value directly in the foundation `PropertyStore` (via
 * the cross-thread typed-property bus) and also seeds a process-wide
 * typed cache for pre-run / cross-thread read-back. The getters read
 * that typed value straight - no parsing.
 *
 * `bind-text="..."` markup still observes a typed write: there is no
 * separate legacy-`Signals` mirror (post-wave-D there is no `Signals`
 * HashMap to mirror into), but the per-tick `apply_text_bindings`
 * system stringifies scalar `PropertyStore` cells on read (I64/F64 ->
 * decimal, Bool -> "true"/"false"), so a bound element reflects the
 * typed value on the next tick without the embedder writing a second,
 * pre-stringified string signal.
 *
 * The `LumenApp*` parameter is reserved for a future per-app
 * store; the current implementation only null-checks it, so
 * passing NULL is supported.
 *
 * Each accessor returns LUMEN_OK on success or LUMEN_ERR_BAD_ARG
 * when the name is null/non-utf8, the out pointer is null, or the
 * signal has never been set via a typed setter. Call
 * `lumen_status_message()` for a static, human-readable description
 * of the status code (handy for embedders that log on non-OK
 * returns without grabbing the thread-local error string).
 * ============================================================ */

LumenStatus lumen_signal_set_int64 (LumenApp* app, const char* name, int64_t value);
LumenStatus lumen_signal_get_int64 (LumenApp* app, const char* name, int64_t* out);

LumenStatus lumen_signal_set_float64(LumenApp* app, const char* name, double value);
LumenStatus lumen_signal_get_float64(LumenApp* app, const char* name, double* out);

LumenStatus lumen_signal_set_bool  (LumenApp* app, const char* name, bool value);
LumenStatus lumen_signal_get_bool  (LumenApp* app, const char* name, bool* out);

/*
 * RGBA bytes (R, G, B, A - each 0..=255). `rgba` / `out` must
 * point to at least 4 writable bytes.
 */
LumenStatus lumen_signal_set_color (LumenApp* app, const char* name, const uint8_t rgba[4]);
LumenStatus lumen_signal_get_color (LumenApp* app, const char* name, uint8_t out[4]);

/* ============================================================
 * String / array signal read-back (ABI 0.3).
 *
 * The legacy string setters (lumen_signal_set_string / _int / _f64 /
 * _array / clear) previously had no getter. These read back the value
 * the EMBEDDER last pushed through those FFI setters. A write that
 * originates inside the running app (a Rhai `signals.x.set(..)` or a
 * two-way input binding) is not visible here - reading live in-app
 * state cross-thread would require sharing the running app's world
 * across the FFI. The `LumenApp*` parameter is reserved (null-checked
 * only); passing NULL is supported.
 *
 * String-out convention: on success the value is copied into `buf` with
 * a trailing NUL and `*out_len` (if non-NULL) is set to the byte length
 * excluding the NUL. If `buf` is NULL or `buf_len` is too small, no
 * bytes are written, `*out_len` is set to the required capacity (byte
 * length + 1 for the NUL), and LUMEN_ERR_BUFFER_TOO_SMALL is returned -
 * call once with a NULL/zero buffer to size it, then again to fill.
 * ============================================================ */

LumenStatus lumen_signal_get_string(LumenApp* app, const char* name,
                                    char* buf, size_t buf_len, size_t* out_len);

/* Row count of an array signal into `*out_len`. */
LumenStatus lumen_signal_array_len (LumenApp* app, const char* name, size_t* out_len);

/* One field of one row (record-shaped field -> stringified value),
 * copied out per the string-out convention above. */
LumenStatus lumen_signal_array_get_field(LumenApp* app, const char* name, size_t row,
                                         const char* field,
                                         char* buf, size_t buf_len, size_t* out_len);

/*
 * Scalar snapshot of a dynamic DOM event (ABI 0.10), passed by pointer to a
 * LumenEventFn. The string fields (type / key / value) are read separately via
 * lumen_event_type / _key / _value. Hand-written here: the struct is only
 * reachable through the hand-written lumen_on, so cbindgen does not emit it.
 * `#[repr(C)]` on the Rust side; keep the field order and types in lockstep.
 */
typedef struct LumenEvent {
    LumenNode target;         /* packed node handle */
    LumenNode current_target; /* packed node handle of the running listener */
    double local_x;           /* pointer x relative to the target */
    double local_y;
    double client_x;          /* pointer x in window coordinates */
    double client_y;
    double delta_x;           /* wheel delta */
    double delta_y;
    int64_t button;           /* 0 primary, 1 middle, 2 secondary, -1 none */
    uint8_t shift;            /* modifier flags, 0 / 1 */
    uint8_t ctrl;
    uint8_t alt;
    uint8_t super_;
} LumenEvent;

/*
 * Dynamic DOM event callback (ABI 0.10). Fires when a bound event reaches
 * `node` during capture -> target -> bubble propagation. `event` is borrowed
 * for the call; copy anything retained. Read the string fields with
 * lumen_event_type / _key / _value and control propagation with
 * lumen_event_prevent_default / _stop_propagation /
 * _stop_immediate_propagation (declared in lumen_simple.h). `user_data` is the
 * pointer passed to lumen_on. Hand-written here: cbindgen renders the
 * Option<extern fn> parameter of lumen_on as an unusable struct.
 */
typedef void (*LumenEventFn)(const LumenEvent* event, void* user_data);

/*
 * Bind `callback` to `node` for `event_type` (e.g. "click", "keydown"). A
 * non-zero `capture` registers a capture-phase listener. Returns an off token
 * (0 on a bad argument); unbind with lumen_off. Thread-safe.
 */
LumenEventToken lumen_on(LumenNode node,
                         const char* event_type,
                         int capture,
                         LumenEventFn callback,
                         void* user_data);

/*
 * Returns a static, NUL-terminated UTF-8 description of `status`.
 * Lives for the program's lifetime; do not free.
 */
const char* lumen_status_message  (LumenStatus status);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* LUMEN_H */
