//! `version` source resolution: the plugin cache and `lumen.lock`.
//!
//! A `[[plugins]] version = "1.2"` entry resolves against the per-user
//! plugin cache, where the registry client installs prebuilt, per-platform
//! cdylibs as `<cache>/<name>/<version>/<platform library file>`. This
//! module is the resolution half only; nothing here talks to the network,
//! and a version absent from the cache is an error that says so.
//!
//! `lumen.lock`, beside `lumen.toml`, pins what a requirement resolved to:
//! the exact version plus a sha256 per platform. Committing it makes the
//! next build reuse the pinned version and refuse a cached cdylib whose
//! bytes changed. A platform records its checksum the first time it builds;
//! from then on that platform verifies against it. The file is regenerated
//! deterministically; edit `lumen.toml`, not the lock.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::config::library_spellings;

/// The lock file name, beside `lumen.toml`.
pub const LOCK_FILE: &str = "lumen.lock";

/// The checksum key for the running host: `<arch>-<os>`.
pub fn platform_key() -> String {
    format!("{}-{}", std::env::consts::ARCH, std::env::consts::OS)
}

/// The plugin cache root: `$LUMEN_PLUGIN_CACHE`, else `~/.lumen/plugins`
/// (`%LOCALAPPDATA%\Programs\Lumen\plugins` on Windows, matching the MSI
/// install prefix).
pub fn cache_root() -> Result<PathBuf, String> {
    if let Some(dir) = std::env::var_os("LUMEN_PLUGIN_CACHE").filter(|v| !v.is_empty()) {
        return Ok(PathBuf::from(dir));
    }
    #[cfg(windows)]
    {
        std::env::var_os("LOCALAPPDATA")
            .filter(|v| !v.is_empty())
            .map(|d| {
                PathBuf::from(d)
                    .join("Programs")
                    .join("Lumen")
                    .join("plugins")
            })
            .ok_or_else(|| "plugin cache: %LOCALAPPDATA% is not set".to_string())
    }
    #[cfg(not(windows))]
    {
        std::env::var_os("HOME")
            .filter(|v| !v.is_empty())
            .map(|d| PathBuf::from(d).join(".lumen").join("plugins"))
            .ok_or_else(|| "plugin cache: $HOME is not set".to_string())
    }
}

/// One locked plugin: the exact version a requirement resolved to, plus the
/// verified cdylib checksum per platform.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LockEntry {
    pub name: String,
    pub version: String,
    /// `<arch>-<os>` -> lowercase hex sha256 of that platform's cdylib.
    #[serde(default)]
    pub checksums: BTreeMap<String, String>,
}

#[derive(Debug, Default, serde::Serialize, serde::Deserialize)]
struct LockDoc {
    version: u32,
    #[serde(default, rename = "plugin")]
    plugins: Vec<LockEntry>,
}

/// The parsed `lumen.lock`, with change tracking so an unchanged lock is
/// never rewritten.
#[derive(Debug)]
pub struct LockFile {
    path: PathBuf,
    doc: LockDoc,
    dirty: bool,
}

impl LockFile {
    /// Read `<app_dir>/lumen.lock`; a missing file is an empty lock.
    pub fn read(app_dir: &Path) -> Result<Self, String> {
        let path = app_dir.join(LOCK_FILE);
        let doc = match std::fs::read_to_string(&path) {
            Ok(text) => {
                let doc = toml::from_str::<LockDoc>(&text)
                    .map_err(|e| format!("{}: {e}", path.display()))?;
                if doc.version != 1 {
                    return Err(format!(
                        "{}: lock format version {} is newer than this lumenc understands; \
                         update lumenc or delete the lock to regenerate it",
                        path.display(),
                        doc.version
                    ));
                }
                doc
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => LockDoc {
                version: 1,
                plugins: Vec::new(),
            },
            Err(e) => return Err(format!("{}: {e}", path.display())),
        };
        Ok(LockFile {
            path,
            doc,
            dirty: false,
        })
    }

    fn entry_mut(&mut self, name: &str) -> Option<&mut LockEntry> {
        self.doc.plugins.iter_mut().find(|e| e.name == name)
    }

    /// Write the lock back if anything changed.
    pub fn store(&self) -> Result<(), String> {
        if !self.dirty {
            return Ok(());
        }
        let mut doc = LockDoc {
            version: self.doc.version,
            plugins: self.doc.plugins.clone(),
        };
        doc.plugins.sort_by(|a, b| a.name.cmp(&b.name));
        let header = "# Generated by lumenc from the [[plugins]] declarations in lumen.toml.\n\
                      # Commit this file; edit lumen.toml, not this one.\n";
        let body = toml::to_string(&doc).map_err(|e| e.to_string())?;
        std::fs::write(&self.path, format!("{header}{body}"))
            .map_err(|e| format!("{}: {e}", self.path.display()))
    }
}

/// Resolve a `version` requirement for `name` to a cached cdylib, pinning
/// the outcome in the lock. See the module docs for the resolution rules.
pub fn resolve_version_source(
    name: &str,
    requirement: &str,
    lock: &mut LockFile,
) -> Result<PathBuf, String> {
    let req = semver::VersionReq::parse(requirement)
        .map_err(|e| format!("plugin '{name}': bad version requirement '{requirement}': {e}"))?;
    let root = cache_root().map_err(|e| format!("plugin '{name}': {e}"))?;
    let plugin_dir = root.join(name);

    // The pinned version wins as long as it still satisfies the (possibly
    // edited) requirement; otherwise re-resolve against the cache.
    let pinned = lock
        .entry_mut(name)
        .map(|e| e.version.clone())
        .filter(|v| semver::Version::parse(v).is_ok_and(|v| req.matches(&v)));
    let version = match pinned {
        Some(v) => v,
        None => {
            let best = cached_versions(&plugin_dir)
                .into_iter()
                .filter(|v| req.matches(v))
                .max()
                .ok_or_else(|| {
                    format!(
                        "plugin '{name}': no cached version matches '{requirement}' under {}; \
                         install the plugin into the cache or use a `path` source \
                         (the registry client is not wired up yet)",
                        plugin_dir.display()
                    )
                })?;
            best.to_string()
        }
    };

    let version_dir = plugin_dir.join(&version);
    if !version_dir.is_dir() {
        // The lock pin points at a version this machine has not cached (a
        // fresh clone, or a cache root that does not exist). Saying "no
        // library for this platform" here would send the user hunting for
        // the wrong problem.
        return Err(format!(
            "plugin '{name}': the locked version {version} is not in the plugin cache ({}); \
             install it there or use a `path` source (the registry client is not wired up yet)",
            version_dir.display()
        ));
    }
    let lib = library_spellings(name)
        .iter()
        .map(|f| version_dir.join(f))
        .find(|p| p.is_file())
        .ok_or_else(|| {
            format!(
                "plugin '{name}': version {version} is in the cache but holds no library for \
                 this platform ({})",
                version_dir.display()
            )
        })?;
    let checksum =
        sha256_file(&lib).map_err(|e| format!("plugin '{name}': {}: {e}", lib.display()))?;

    let platform = platform_key();
    match lock.entry_mut(name) {
        Some(entry) if entry.version == version => match entry.checksums.get(&platform) {
            Some(want) if *want != checksum => {
                return Err(format!(
                    "plugin '{name}': checksum mismatch for {} version {version}: lumen.lock has \
                     {want}, the cached file is {checksum}; the cache was tampered with or the \
                     lock is stale - delete the cached version or the lock entry to re-pin",
                    platform
                ));
            }
            Some(_) => {}
            None => {
                entry.checksums.insert(platform, checksum);
                lock.dirty = true;
            }
        },
        Some(entry) => {
            entry.version = version;
            entry.checksums = BTreeMap::from([(platform, checksum)]);
            lock.dirty = true;
        }
        None => {
            lock.doc.plugins.push(LockEntry {
                name: name.to_string(),
                version,
                checksums: BTreeMap::from([(platform, checksum)]),
            });
            lock.dirty = true;
        }
    }
    Ok(lib)
}

/// Every semver-named subdirectory of one plugin's cache dir.
fn cached_versions(plugin_dir: &Path) -> Vec<semver::Version> {
    let Ok(entries) = std::fs::read_dir(plugin_dir) else {
        return Vec::new();
    };
    entries
        .flatten()
        .filter(|e| e.path().is_dir())
        .filter_map(|e| semver::Version::parse(&e.file_name().to_string_lossy()).ok())
        .collect()
}

fn sha256_file(path: &Path) -> Result<String, std::io::Error> {
    use sha2::{Digest, Sha256};
    let bytes = std::fs::read(path)?;
    let digest = Sha256::digest(&bytes);
    Ok(digest.iter().map(|b| format!("{b:02x}")).collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    struct CacheEnv {
        _guard: std::sync::MutexGuard<'static, ()>,
        root: PathBuf,
        app: PathBuf,
    }

    /// Serialize the tests that set `LUMEN_PLUGIN_CACHE` (process-global).
    fn cache_env(tag: &str) -> CacheEnv {
        static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let guard = LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let base = std::env::temp_dir().join(format!("lumenc-plugin-resolve-{tag}"));
        let _ = std::fs::remove_dir_all(&base);
        let root = base.join("cache");
        let app = base.join("app");
        std::fs::create_dir_all(&root).unwrap();
        std::fs::create_dir_all(&app).unwrap();
        unsafe { std::env::set_var("LUMEN_PLUGIN_CACHE", &root) };
        CacheEnv {
            _guard: guard,
            root,
            app,
        }
    }

    fn install(root: &Path, name: &str, version: &str, bytes: &[u8]) -> PathBuf {
        let dir = root.join(name).join(version);
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join(&library_spellings(name)[0]);
        std::fs::write(&file, bytes).unwrap();
        file
    }

    #[test]
    fn resolves_highest_matching_and_pins() {
        let env = cache_env("pin");
        install(&env.root, "demo", "1.1.0", b"old");
        let newest = install(&env.root, "demo", "1.4.2", b"new");
        install(&env.root, "demo", "2.0.0", b"next-major");

        let mut lock = LockFile::read(&env.app).unwrap();
        let hit = resolve_version_source("demo", "1.2", &mut lock).unwrap();
        assert_eq!(hit, newest);
        lock.store().unwrap();

        let text = std::fs::read_to_string(env.app.join(LOCK_FILE)).unwrap();
        assert!(text.contains("version = \"1.4.2\""), "{text}");
        assert!(text.contains(&platform_key()), "{text}");
    }

    #[test]
    fn the_pin_wins_over_a_newer_cached_version() {
        let env = cache_env("stable-pin");
        let pinned = install(&env.root, "demo", "1.1.0", b"pinned");
        let mut lock = LockFile::read(&env.app).unwrap();
        resolve_version_source("demo", "1", &mut lock).unwrap();
        lock.store().unwrap();

        // A newer matching version arrives in the cache; the pin holds.
        install(&env.root, "demo", "1.9.0", b"newer");
        let mut lock = LockFile::read(&env.app).unwrap();
        let hit = resolve_version_source("demo", "1", &mut lock).unwrap();
        assert_eq!(hit, pinned);
    }

    #[test]
    fn an_edited_requirement_repins() {
        let env = cache_env("repin");
        install(&env.root, "demo", "1.1.0", b"one");
        let two = install(&env.root, "demo", "2.3.0", b"two");
        let mut lock = LockFile::read(&env.app).unwrap();
        resolve_version_source("demo", "1", &mut lock).unwrap();
        lock.store().unwrap();

        let mut lock = LockFile::read(&env.app).unwrap();
        let hit = resolve_version_source("demo", "2", &mut lock).unwrap();
        assert_eq!(hit, two);
        lock.store().unwrap();
        let text = std::fs::read_to_string(env.app.join(LOCK_FILE)).unwrap();
        assert!(text.contains("version = \"2.3.0\""), "{text}");
    }

    #[test]
    fn a_tampered_cache_is_refused() {
        let env = cache_env("tamper");
        let file = install(&env.root, "demo", "1.0.0", b"original");
        let mut lock = LockFile::read(&env.app).unwrap();
        resolve_version_source("demo", "1", &mut lock).unwrap();
        lock.store().unwrap();

        std::fs::write(&file, b"tampered").unwrap();
        let mut lock = LockFile::read(&env.app).unwrap();
        let err = resolve_version_source("demo", "1", &mut lock).unwrap_err();
        assert!(err.contains("checksum mismatch"), "{err}");
    }

    #[test]
    fn an_empty_cache_names_the_fix() {
        let env = cache_env("empty");
        let mut lock = LockFile::read(&env.app).unwrap();
        let err = resolve_version_source("ghost", "1.2", &mut lock).unwrap_err();
        assert!(err.contains("no cached version matches"), "{err}");
        assert!(err.contains("registry client is not wired up yet"), "{err}");
    }

    #[test]
    fn the_cache_root_falls_back_to_home_and_errors_without_one() {
        let env = cache_env("root-fallback");
        drop(env); // keep the mutex path exercised the same way
        static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let _guard = LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let saved_cache = std::env::var_os("LUMEN_PLUGIN_CACHE");
        let saved_home = std::env::var_os("HOME");
        unsafe { std::env::remove_var("LUMEN_PLUGIN_CACHE") };
        unsafe { std::env::set_var("HOME", "/home/someone") };
        assert_eq!(
            cache_root().unwrap(),
            PathBuf::from("/home/someone/.lumen/plugins")
        );
        unsafe { std::env::remove_var("HOME") };
        let err = cache_root().unwrap_err();
        assert!(err.contains("HOME"), "{err}");
        if let Some(v) = saved_home {
            unsafe { std::env::set_var("HOME", v) };
        }
        if let Some(v) = saved_cache {
            unsafe { std::env::set_var("LUMEN_PLUGIN_CACHE", v) };
        }
    }

    #[test]
    fn a_newer_lock_format_is_refused() {
        let env = cache_env("lock-v2");
        std::fs::write(env.app.join(LOCK_FILE), "version = 2\n").unwrap();
        let err = LockFile::read(&env.app).unwrap_err();
        assert!(err.contains("lock format version 2"), "{err}");
        assert!(err.contains("update lumenc"), "{err}");
    }

    #[cfg(unix)]
    #[test]
    fn an_unreadable_lock_is_an_error_naming_the_file() {
        use std::os::unix::fs::PermissionsExt;
        let env = cache_env("lock-unreadable");
        let lock_path = env.app.join(LOCK_FILE);
        std::fs::write(&lock_path, "version = 1\n").unwrap();
        std::fs::set_permissions(&lock_path, std::fs::Permissions::from_mode(0o000)).unwrap();
        let err = LockFile::read(&env.app).unwrap_err();
        std::fs::set_permissions(&lock_path, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert!(err.contains(LOCK_FILE), "{err}");
    }

    #[test]
    fn a_cached_version_without_this_platforms_library_says_so() {
        let env = cache_env("no-lib");
        std::fs::create_dir_all(env.root.join("demo").join("1.0.0")).unwrap();
        let mut lock = LockFile::read(&env.app).unwrap();
        let err = resolve_version_source("demo", "1", &mut lock).unwrap_err();
        assert!(err.contains("holds no library for this platform"), "{err}");
    }

    #[test]
    fn a_lock_entry_missing_this_platforms_checksum_gains_it() {
        let env = cache_env("gain-checksum");
        install(&env.root, "demo", "1.0.0", b"bytes");
        // A lock pinned on another platform: same version, no checksum for
        // this one.
        std::fs::write(
            env.app.join(LOCK_FILE),
            "version = 1\n\n[[plugin]]\nname = \"demo\"\nversion = \"1.0.0\"\n",
        )
        .unwrap();
        let mut lock = LockFile::read(&env.app).unwrap();
        resolve_version_source("demo", "1", &mut lock).unwrap();
        assert!(lock.dirty);
        lock.store().unwrap();
        let text = std::fs::read_to_string(env.app.join(LOCK_FILE)).unwrap();
        assert!(text.contains(&platform_key()), "{text}");
    }

    #[test]
    fn a_pinned_version_missing_from_the_cache_names_the_real_problem() {
        let env = cache_env("pinned-absent");
        install(&env.root, "demo", "1.4.2", b"bytes");
        let mut lock = LockFile::read(&env.app).unwrap();
        resolve_version_source("demo", "1", &mut lock).unwrap();
        lock.store().unwrap();

        // Fresh-clone shape: the lock survives, the cache does not.
        std::fs::remove_dir_all(env.root.join("demo")).unwrap();
        let mut lock = LockFile::read(&env.app).unwrap();
        let err = resolve_version_source("demo", "1", &mut lock).unwrap_err();
        assert!(
            err.contains("locked version 1.4.2 is not in the plugin cache"),
            "{err}"
        );
        assert!(!err.contains("is in the cache but"), "{err}");
    }

    #[test]
    fn an_unchanged_lock_is_not_rewritten() {
        let env = cache_env("no-rewrite");
        install(&env.root, "demo", "1.0.0", b"bytes");
        let mut lock = LockFile::read(&env.app).unwrap();
        resolve_version_source("demo", "1", &mut lock).unwrap();
        lock.store().unwrap();
        let first = std::fs::metadata(env.app.join(LOCK_FILE))
            .unwrap()
            .modified()
            .unwrap();

        let mut lock = LockFile::read(&env.app).unwrap();
        resolve_version_source("demo", "1", &mut lock).unwrap();
        assert!(!lock.dirty);
        lock.store().unwrap();
        let second = std::fs::metadata(env.app.join(LOCK_FILE))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(first, second);
    }
}
