/*
 * AUTO-GENERATED by cbindgen - do not edit by hand.
 *
 * Generated from lumen for the simple-side C ABI (status enum,
 * version macro, app lifecycle entry points). The complex tagged-
 * union types and callback signatures live in the hand-written
 * `lumen.h`, which includes this file.
 */


#ifndef LUMEN_SIMPLE_H
#define LUMEN_SIMPLE_H

#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

/*
 Major ABI version. Bump on breaking layout/signature changes.
 */
#define LUMEN_ABI_MAJOR 0

/*
 Minor ABI version. Bump on additive changes (new exports, new variants at the end of enums).

 0.4 added the change-subscription surface: [`LumenWatchFn`] +
 [`lumen_signal_watch`], a commit-fired signal-change callback wired
 through the running app's [`PropertyStore`] dirty machinery (no
 polling thread).

 0.5 added the graceful-shutdown hook: [`LumenCloseFn`] +
 [`lumen_app_on_close`], a close callback that fires on the OS close
 request (window button; Unix SIGINT/SIGTERM) *before* teardown and
 can veto the close by returning 0.

 0.6 added file-based-pages navigation: [`lumen_navigate`],
 [`lumen_navigate_back`], [`lumen_navigate_forward`], and
 [`lumen_current_page`], writing the reserved `route.request` cell through
 the shared `lumen_core::nav` bus (the same surface the script `page()`
 builtin and the Rust SDK use).

 0.7 added the link-not-embed launcher seam: [`lumen_app_new_from_lmna`],
 which builds a [`LumenApp`] from prebuilt LMNA artifact bytes with NO
 parser. The thin `lumenc` launcher compiles source to LMNA bytes in-process
 and hands them across this ABI to a dlopen'd liblumen, instead of
 static-linking the runtime. `lumen_app_new(dir)` is unchanged (still parses
 via the bundled parser). See `docs/design/link-not-embed.md`.

 0.8 added the dynamic DOM read side: [`LumenNode`], [`LumenNodeList`] +
 [`lumen_nodelist_free`] / [`lumen_nodelist_get`], and the query +
 traversal getters ([`lumen_query`], [`lumen_query_len`],
 [`lumen_query_single`], [`lumen_get_by_id`], [`lumen_document`],
 [`lumen_node_parent`] and siblings, [`lumen_node_children`],
 [`lumen_node_closest`], [`lumen_node_valid`]). All read the process-shared
 per-tick DOM snapshot; additive, so a minor bump.

 0.9 added the dynamic DOM write side + `window` / `document` / `history`:
 [`lumen_node_set_attr`] / [`lumen_node_remove_attr`] /
 [`lumen_node_set_text`], class-list edits
 ([`lumen_node_class_add`] / `_remove` / `_toggle`), inline style
 ([`lumen_node_set_style`] / [`lumen_node_remove_style`]), structure
 ([`lumen_node_spawn`], [`lumen_node_clone`], [`lumen_node_append`],
 [`lumen_node_insert_before`], [`lumen_node_set_parent`],
 [`lumen_node_replace_with`], [`lumen_node_remove`]), and the window /
 history / document entry points ([`lumen_window_set_href`],
 [`lumen_window_reload`], [`lumen_window_set_title`],
 [`lumen_window_set_size`], [`lumen_window_dpr`], [`lumen_history_go`],
 [`lumen_document_spawn`]). Mutations queue on the external DOM bus the
 runtime drains each tick; additive, so a minor bump.

 0.10 added the dynamic DOM event side (phase 4): register a C callback +
 user data against a node and event type with [`lumen_on`]
 (capture-phase opt-in), unbind with [`lumen_off`]. The callback receives a
 [`LumenEvent`] (scalar fields) plus accessor functions for the string
 fields ([`lumen_event_type`], [`lumen_event_key`], [`lumen_event_value`])
 and the propagation controls ([`lumen_event_prevent_default`],
 [`lumen_event_stop_propagation`], [`lumen_event_stop_immediate_propagation`]).
 The runtime invokes registered callbacks during capture -> target ->
 bubble propagation; additive, so a minor bump.

 0.11 added the low-level introspection read side (phase 5): post-layout
 geometry ([`lumen_node_rect`], [`lumen_node_content_rect`],
 [`lumen_node_scroll`], [`lumen_node_is_visible`], [`lumen_node_z_index`]),
 full computed style / attributes / inline style / component reads as
 key-value buffers ([`lumen_node_computed_style`], [`lumen_node_attrs`],
 [`lumen_node_inline_style`], [`lumen_node_component`]), class / component
 name lists ([`lumen_node_classes`], [`lumen_node_components`]), tree
 serialization ([`lumen_node_outer_markup`], [`lumen_dump_tree`]), entity
 id ([`lumen_node_entity_id`]), and global state ([`lumen_pointer_state`],
 [`lumen_frame_info`], [`lumen_signals_all`]), with the
 [`lumen_kvlist_free`] / [`lumen_strlist_free`] / [`lumen_string_free`]
 releasers. Additive, so a minor bump.

 0.12 added guarded markup injection (phase 6): read a node's children as
 `.lmn`-ish text with [`lumen_node_inner_markup`], and replace them from a
 markup fragment with [`lumen_node_set_inner_markup`]. The setter parses
 through the injected front-end (present on the from-source run path, a
 no-op on the precompiled-artifact path) and must not be fed untrusted
 content. Additive, so a minor bump.

 0.13 unified the scalar signal surface into one typed family:
 [`lumen_signal_set_str`] / [`lumen_signal_get_str`] join the existing
 int64 / float64 / bool / color pairs, the older stringifying setters
 and their string getter are removed, and the unread `LumenApp*` first
 parameter is gone from every typed accessor and from
 [`lumen_signal_array_len`] / [`lumen_signal_array_get_field`]. Kept
 names changed arity, so embedders rebuild against the new header
 rather than relinking.

 0.14 unified exposed-callback registration the same way: `LumenFn` is
 now the out-parameter callback, [`lumen_app_expose`] takes it, and the
 by-value callback type along with `lumen_app_expose_v2` are removed.
 Existing callbacks change signature, so embedders rebuild against the
 new header rather than relinking.
 */
#define LUMEN_ABI_MINOR 14

/*
 Patch ABI version. Bump on non-API metadata changes (docs, code, etc.).
 */
#define LUMEN_ABI_PATCH 0

/*
 Packed runtime ABI version `(major << 16) | (minor << 8) | patch`.
 Mirrored in `lumen.h` as `LUMEN_API_VERSION`. Embedders compare at
 runtime to refuse a header / shared-library mismatch.
 */
#define LUMEN_ABI_VERSION (((LUMEN_ABI_MAJOR << 16) | (LUMEN_ABI_MINOR << 8)) | LUMEN_ABI_PATCH)

/*
 Opaque packed node handle. `0` means "no node".
 */
typedef uint64_t LumenNode;

/*
 Owned list of node handles returned by a query / children call. Free
 with [`lumen_nodelist_free`]; index with [`lumen_nodelist_get`].
 */
typedef struct {
    /*
     Heap pointer to `len` contiguous [`LumenNode`] handles, or null
     when `len == 0`.
     */
    LumenNode *ptr;
    /*
     Number of handles.
     */
    size_t len;
} LumenNodeList;

/*
 Post-layout box (design 4.7 `rect()` / `content_rect()`). Local `x` / `y`
 are relative to the parent; `client_*` are window coordinates.
 */
typedef struct {
    /*
     Local x.
     */
    double x;
    /*
     Local y.
     */
    double y;
    /*
     Width.
     */
    double width;
    /*
     Height.
     */
    double height;
    /*
     Window-space x.
     */
    double client_x;
    /*
     Window-space y.
     */
    double client_y;
} LumenRect;

/*
 Scroll offsets + travel limits (`scroll()`).
 */
typedef struct {
    /*
     Horizontal offset.
     */
    double x;
    /*
     Vertical offset.
     */
    double y;
    /*
     Max horizontal offset.
     */
    double max_x;
    /*
     Max vertical offset.
     */
    double max_y;
} LumenScroll;

/*
 One `(key, value)` pair in a [`LumenKVList`]. Both are owned, UTF-8,
 NUL-terminated strings freed by [`lumen_kvlist_free`].
 */
typedef struct {
    /*
     Owned key.
     */
    char *key;
    /*
     Owned value.
     */
    char *value;
} LumenKV;

/*
 Owned key-value buffer returned by the string-map introspection reads.
 Free with [`lumen_kvlist_free`].
 */
typedef struct {
    /*
     Heap pointer to `len` pairs, or null when `len == 0`.
     */
    LumenKV *ptr;
    /*
     Number of pairs.
     */
    size_t len;
} LumenKVList;

/*
 Owned string buffer returned by `classes` / `components`. Free with
 [`lumen_strlist_free`].
 */
typedef struct {
    /*
     Heap pointer to `len` owned C strings, or null when `len == 0`.
     */
    char **ptr;
    /*
     Number of strings.
     */
    size_t len;
} LumenStrList;

/*
 Pointer state snapshot (`pointer_state()`).
 */
typedef struct {
    /*
     Window-space x.
     */
    double x;
    /*
     Window-space y.
     */
    double y;
    /*
     Non-zero while the pointer is inside the window.
     */
    int inside;
    /*
     Bit 0 set while the primary button is held.
     */
    uint32_t buttons;
    /*
     Shift held.
     */
    int shift;
    /*
     Control held.
     */
    int ctrl;
    /*
     Alt held.
     */
    int alt;
    /*
     Super / Command held.
     */
    int super_;
} LumenPointerState;

/*
 Per-frame counters (`frame_info()`).
 */
typedef struct {
    /*
     Monotonic tick counter.
     */
    uint64_t frame;
    /*
     Milliseconds since the previous frame.
     */
    double dt_ms;
    /*
     Layout-dirty element count.
     */
    uint64_t dirty_count;
} LumenFrameInfo;

/*
 Off token returned by [`lumen_on`]; pass to [`lumen_off`] to unbind.
 */
typedef uint64_t LumenEventToken;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Returns the packed ABI version this library was compiled with.
 Compare against `LUMEN_API_VERSION` from `lumen.h` at startup.
 */
 uint32_t lumen_abi_version(void) ;

/*
 Allocate a new app rooted at `dir` (UTF-8, NUL-terminated). The
 directory must exist and contain `lumen.toml` and/or `src/main.lmn`.
 Returns null on error; call `lumen_last_error` for details.

 ABI 0.3 made this validation eager: prior versions accepted any
 path and only surfaced a bad directory later, inside
 `lumen_app_run` (i.e. only after opening a window). The directory is
 now `stat`-ed up front and its contents checked, so a bad app
 directory fails at construction time with a null return.
 */
 LumenApp *lumen_app_new(const char *dir) ;

/*
 Allocate a new app from prebuilt LMNA artifact bytes (ABI 0.7). `data`
 points to `len` bytes of a `lumenc`-compiled artifact (magic `LMNA`);
 Lumen copies them in immediately, so the caller may free `data` as soon as
 this returns. `base_dir` (UTF-8, NUL-terminated, or null) is the directory
 relative asset paths in the artifact resolve against; null means the
 current directory.

 This is the link-not-embed launcher seam: the thin `lumenc` launcher
 compiles source to LMNA bytes in-process (it has the parser) and hands them
 here, so the runtime runs with NO parser and never touches a source file.
 Contrast [`lumen_app_new`], which takes a source directory and parses via
 the bundled parser.

 Returns null on error (null/empty `data`, or `base_dir` not UTF-8); call
 [`lumen_last_error`] for details. The artifact bytes themselves are
 validated lazily at run time (`lumen_app_run` / `lumen_app_run_headless`),
 where a bad magic / version surfaces as an error status.
 */
 LumenApp *lumen_app_new_from_lmna(const uint8_t *data, size_t len, const char *base_dir) ;

/*
 Override the window title (default: derived from `lumen.toml` or
 the directory name).
 */
 LumenStatus lumen_app_set_title(LumenApp *app, const char *title) ;

/*
 Override the initial window size in logical pixels.
 */
 LumenStatus lumen_app_set_size(LumenApp *app, uint32_t w, uint32_t h) ;

/*
 Drop the app handle without running. Safe to call on null.
 */
 void lumen_app_free(LumenApp *app) ;

/*
 Consume the app handle and enter the Lumen event loop. Blocks
 until the window closes. After this returns, `app` is freed -
 do not call `lumen_app_free` on the same pointer.
 */
 LumenStatus lumen_app_run(LumenApp *app) ;

/*
 Last error message set by any `lumen_*` call on this thread.
 Returns null if no error has been recorded on this thread AND no
 error has been recorded globally. The pointer is valid until the
 next `lumen_*` call on this thread that produces an error.

 W6.12 added a global fallback: when the thread-local slot is
 empty (the common multi-thread embedder mistake of writing on
 thread A and reading on thread B), we return the most recent
 error from any thread instead of null.
 */
 const char *lumen_last_error(void) ;

/*
 Returns the most recent error message recorded by any thread.
 May return null if no error has ever been recorded. The returned
 pointer is valid until the next `lumen_*` call anywhere in the
 process that produces an error.

 Distinguished from [`lumen_last_error`] for embedders that
 explicitly want the global slot and don't want the TLS fallback.
 */
 const char *lumen_last_error_global(void) ;

/*
 Navigate the active page to `path` (UTF-8, NUL-terminated). `path` is a
 page path (`"settings"`, `"/user/7"`, `"/"`), resolved by longest
 existing `.lmn` prefix - not a URL scheme. Equivalent to the script
 `page("...")` command and the Rust SDK `Signals::navigate`. Thread-safe.
 */
 LumenStatus lumen_navigate(const char *path) ;

/*
 Step one entry back in the in-memory history stack (desktop). No-op at the
 start of history. Thread-safe.
 */
 LumenStatus lumen_navigate_back(void) ;

/*
 Step one entry forward in the in-memory history stack (desktop). No-op at
 the end of history. Thread-safe.
 */
 LumenStatus lumen_navigate_forward(void) ;

/*
 Read the current active page key into `buf` (UTF-8 + trailing NUL),
 following the shared string-out convention: on success `*out_len` (when
 non-null) is the byte length excluding the NUL; when `buf` is null or too
 small, `*out_len` is set to the required capacity and
 [`LumenStatus::ErrBufferTooSmall`] is returned. Empty before the first
 page mounts. Thread-safe (reads the `lumen_core::nav` current-page mirror,
 which lags a resolved navigation by at most one tick).
 */
 LumenStatus lumen_current_page(char *buf, size_t buf_len, size_t *out_len) ;

/*
 Clear a signal (scalar => empty string, array => empty vec).
 */
 LumenStatus lumen_signal_clear(const char *name) ;

/*
 Set a scalar signal to a UTF-8 string. A null `value` writes an empty
 string. Thread-safe.

 Pushes a `PropertyValue::Str` through the foundation typed-property
 bus, so `bind-text="..."` markup observes the new string on the next
 tick. Mirrors the write into the FFI-local cache for pre-run
 read-back.
 */
 LumenStatus lumen_signal_set_str(const char *name, const char *value) ;

/*
 Read a scalar signal as a UTF-8 string into a caller-provided buffer.

 On success copies the value plus a trailing NUL into `buf` and, when
 `out_len` is non-null, sets `*out_len` to the byte length (excluding
 the NUL). When `buf` is null or `buf_len` is too small, sets
 `*out_len` to the required capacity (byte length + 1) and returns
 [`LumenStatus::ErrBufferTooSmall`] without writing `buf`; call once
 with a null/zero buffer to size it, then again to fill.

 Returns [`LumenStatus::ErrBadArg`] when `name` is null / non-UTF-8, or
 when the signal holds no string.

 Scope: this reads back the string the embedder last pushed through
 the FFI (a `clear` leaves an empty string). A string written inside
 the running app lands in `PropertyStore`, which the cross-thread
 mirror keeps for numbers, bools, and colors only, so it is not
 visible here.
 */
 LumenStatus lumen_signal_get_str(const char *name, char *buf, size_t buf_len, size_t *out_len) ;

/*
 Set a scalar signal to a 64-bit signed integer, typed.

 Pushes a `PropertyValue::I64` through the foundation typed-property
 bus so the receiving cell in `PropertyStore` keeps the typed variant
 (no stringify-on-write, no parse-on-read). Mirrors the write into the
 FFI-local cache for pre-run read-back.
 */
 LumenStatus lumen_signal_set_int64(const char *name, int64_t value) ;

/*
 Read a scalar signal as a 64-bit signed integer, typed. Returns
 [`LumenStatus::ErrBadArg`] when the signal holds no number.

 Peeks the foundation typed-property bus snapshot first (catches
 pending pre-run writes that haven't been drained yet) before falling
 back to the local cache.
 */
 LumenStatus lumen_signal_get_int64(const char *name, int64_t *out) ;

/*
 Set a scalar signal to an IEEE-754 double, typed.

 Pushes `PropertyValue::F64` through the typed-property bus so the
 `PropertyStore` cell receives the typed variant directly.
 */
 LumenStatus lumen_signal_set_float64(const char *name, double value) ;

/*
 Read a scalar signal as an IEEE-754 double, typed.
 */
 LumenStatus lumen_signal_get_float64(const char *name, double *out) ;

/*
 Set a scalar signal to a boolean, typed.

 Pushes `PropertyValue::Bool` through the typed-property bus so the
 `PropertyStore` cell receives the typed variant directly.
 */
 LumenStatus lumen_signal_set_bool(const char *name, bool value) ;

/*
 Read a scalar signal as a boolean, typed.
 */
 LumenStatus lumen_signal_get_bool(const char *name, bool *out) ;

/*
 Set a scalar signal to a 4-byte RGBA color (each channel in 0..=255).
 `rgba` must point to at least 4 bytes (`R`, `G`, `B`, `A`).

 Pushes `PropertyValue::Color` (channels normalised to `[0, 1]`
 floats) through the typed-property bus.
 */
 LumenStatus lumen_signal_set_color(const char *name, const uint8_t *rgba) ;

/*
 Read a scalar signal as a 4-byte RGBA color. `out` must point to at
 least 4 writable bytes.
 */
 LumenStatus lumen_signal_get_color(const char *name, uint8_t *out) ;

/*
 Returns a static, NUL-terminated UTF-8 description of `status`. Useful for
 log messages on a non-OK return without an `lumen_last_error` round-trip
 (which carries the thread-local context message instead of the status
 enum's canonical name). The returned pointer lives for the program's
 lifetime; callers must not free it.
 */
 const char *lumen_status_message(LumenStatus status) ;

/*
 Run a CSS selector against the current DOM snapshot, writing the
 matches (document order) into `*out_list`. On success the caller owns
 the list and must release it with [`lumen_nodelist_free`]. A bad
 selector returns [`LumenStatus::ErrCss`]. Thread-safe.
 */
 LumenStatus lumen_query(const char *selector, LumenNodeList *out_list) ;

/*
 Number of matches for `selector`, written to `*out_len`. Thread-safe.
 */
 LumenStatus lumen_query_len(const char *selector, size_t *out_len) ;

/*
 Bevy `single()` contract: succeed only when `selector` matches exactly
 one node, writing it to `*out`. Zero or many matches returns
 [`LumenStatus::ErrBadArg`] (and sets `*out` to `0`). Thread-safe.
 */
 LumenStatus lumen_query_single(const char *selector, LumenNode *out) ;

/*
 Fast id lookup. Writes the matching node to `*out`, or `0` when no
 element carries `id`. Thread-safe.
 */
 LumenStatus lumen_get_by_id(const char *id, LumenNode *out) ;

/*
 Write the document root node to `*out` (`0` before the first tick).
 Thread-safe.
 */
 LumenStatus lumen_document(LumenNode *out) ;

/*
 Parent of `node` (`0` for a root or unknown handle). Thread-safe.
 */
 LumenStatus lumen_node_parent(LumenNode node, LumenNode *out) ;

/*
 First child of `node` (`0` when none). Thread-safe.
 */
 LumenStatus lumen_node_first_child(LumenNode node, LumenNode *out) ;

/*
 Last child of `node` (`0` when none). Thread-safe.
 */
 LumenStatus lumen_node_last_child(LumenNode node, LumenNode *out) ;

/*
 Next sibling of `node` (`0` when none). Thread-safe.
 */
 LumenStatus lumen_node_next(LumenNode node, LumenNode *out) ;

/*
 Previous sibling of `node` (`0` when none). Thread-safe.
 */
 LumenStatus lumen_node_prev(LumenNode node, LumenNode *out) ;

/*
 Children of `node` in document order, written to `*out_list` (own +
 free with [`lumen_nodelist_free`]). Thread-safe.
 */
 LumenStatus lumen_node_children(LumenNode node, LumenNodeList *out_list) ;

/*
 Nearest ancestor-or-self of `node` matching `selector`, written to
 `*out` (`0` when none). Bad selector returns [`LumenStatus::ErrCss`].
 Thread-safe.
 */
 LumenStatus lumen_node_closest(LumenNode node, const char *selector, LumenNode *out) ;

/*
 Whether `node` is present in the current snapshot (`1`) or not (`0`),
 written to `*out`. The snapshot rebuilds each tick, so a despawned node
 reads `0`. Thread-safe.
 */
 LumenStatus lumen_node_valid(LumenNode node, int *out) ;

/*
 Read the handle at `index` in `list`, written to `*out`. Out-of-range
 (or null list) returns [`LumenStatus::ErrBadArg`]. The iteration
 primitive: walk `0..list.len`. Thread-safe.

 # Safety
 `list` must be a list returned by a query / children call and not yet
 freed.
 */
 LumenStatus lumen_nodelist_get(LumenNodeList list, size_t index, LumenNode *out) ;

/*
 Release a [`LumenNodeList`] returned by a query / children call.
 Double-free / freeing a non-Lumen list is undefined; call once.

 # Safety
 `list` must come from a Lumen query / children call and not have been
 freed already.
 */
 void lumen_nodelist_free(LumenNodeList list) ;

/*
 Post-layout border-box of `node`, written to `*out`. Thread-safe.
 */
 LumenStatus lumen_node_rect(LumenNode node, LumenRect *out) ;

/*
 Content-box (inner box minus padding + border) of `node`. Thread-safe.
 */
 LumenStatus lumen_node_content_rect(LumenNode node, LumenRect *out) ;

/*
 Scroll offsets + limits of `node`, written to `*out`. Thread-safe.
 */
 LumenStatus lumen_node_scroll(LumenNode node, LumenScroll *out) ;

/*
 Effective visibility of `node` (`1` / `0`), written to `*out`.
 */
 LumenStatus lumen_node_is_visible(LumenNode node, int *out) ;

/*
 Resolved stacking order of `node`, written to `*out`.
 */
 LumenStatus lumen_node_z_index(LumenNode node, int *out) ;

/*
 Raw `(index, generation)` of `node`, written to `*out_index` / `*out_gen`.
 */
 LumenStatus lumen_node_entity_id(LumenNode node, uint32_t *out_index, uint32_t *out_gen) ;

/*
 Full computed style of `node` as an owned key-value buffer. Free with
 [`lumen_kvlist_free`]. An inspection call. Thread-safe.
 */
 LumenStatus lumen_node_computed_style(LumenNode node, LumenKVList *out) ;

/*
 Full attribute map of `node`. Free with [`lumen_kvlist_free`].
 */
 LumenStatus lumen_node_attrs(LumenNode node, LumenKVList *out) ;

/*
 Inline-style override map of `node`. Free with [`lumen_kvlist_free`].
 */
 LumenStatus lumen_node_inline_style(LumenNode node, LumenKVList *out) ;

/*
 Field map of `node`'s `name` component. Free with [`lumen_kvlist_free`].
 A non-whitelisted component name returns [`LumenStatus::ErrBadArg`].
 */
 LumenStatus lumen_node_component(LumenNode node, const char *name, LumenKVList *out) ;

/*
 Class list of `node`. Free with [`lumen_strlist_free`].
 */
 LumenStatus lumen_node_classes(LumenNode node, LumenStrList *out) ;

/*
 Names of the whitelisted components present on `node`. Free with
 [`lumen_strlist_free`].
 */
 LumenStatus lumen_node_components(LumenNode node, LumenStrList *out) ;

/*
 Serialize `node`'s subtree to `.lmn`-ish text. Owned C string, free with
 [`lumen_string_free`].
 */
 LumenStatus lumen_node_outer_markup(LumenNode node, char **out) ;

/*
 Serialize `node`'s children (not the node itself) to `.lmn`-ish text --
 the read half of [`lumen_node_set_inner_markup`]. Owned C string, free
 with [`lumen_string_free`].
 */
 LumenStatus lumen_node_inner_markup(LumenNode node, char **out) ;

/*
 Whole-tree structural dump. Owned C string, free with
 [`lumen_string_free`]. An inspection call.
 */
 LumenStatus lumen_dump_tree(char **out) ;

/*
 Current pointer state, written to `*out`. Thread-safe.
 */
 LumenStatus lumen_pointer_state(LumenPointerState *out) ;

/*
 Current frame counters, written to `*out`. Thread-safe.
 */
 LumenStatus lumen_frame_info(LumenFrameInfo *out) ;

/*
 The whole signal set as an owned key-value buffer. Free with
 [`lumen_kvlist_free`]. An inspection call. Thread-safe.
 */
 LumenStatus lumen_signals_all(LumenKVList *out) ;

/*
 Release a [`LumenKVList`] returned by an introspection read.
 */
 void lumen_kvlist_free(LumenKVList list) ;

/*
 Release a [`LumenStrList`] returned by `classes` / `components`.
 */
 void lumen_strlist_free(LumenStrList list) ;

/*
 Release an owned C string returned by `dump_tree` / `outer_markup`.
 */
 void lumen_string_free(char *s) ;

/*
 Set an attribute on `node`. KNOWN attrs (`id` / `class` / `text` /
 `disabled`) route to their typed component; others land in the generic
 attribute map. Thread-safe.
 */
 LumenStatus lumen_node_set_attr(LumenNode node, const char *name, const char *value) ;

/*
 Remove an attribute from `node`. Thread-safe.
 */
 LumenStatus lumen_node_remove_attr(LumenNode node, const char *name) ;

/*
 Replace `node`'s text content. Thread-safe.
 */
 LumenStatus lumen_node_set_text(LumenNode node, const char *text) ;

/*
 Replace `node`'s children with the subtree parsed from `markup`
 (`element.innerHTML = ...`). Parsed by the injected front-end and spawned
 through the same path the `<for>` reconciler uses; a no-op on the
 precompiled-artifact path (no parser linked). Guarded: do not feed
 untrusted content; this injects live markup. Thread-safe.
 */
 LumenStatus lumen_node_set_inner_markup(LumenNode node, const char *markup) ;

/*
 Add one class to `node`'s class list. Thread-safe.
 */
 LumenStatus lumen_node_class_add(LumenNode node, const char *class_) ;

/*
 Remove one class from `node`'s class list. Thread-safe.
 */
 LumenStatus lumen_node_class_remove(LumenNode node, const char *class_) ;

/*
 Toggle one class on `node`'s class list. Thread-safe.
 */
 LumenStatus lumen_node_class_toggle(LumenNode node, const char *class_) ;

/*
 Set an inline style property on `node` (`element.style`). Thread-safe.
 */
 LumenStatus lumen_node_set_style(LumenNode node, const char *name, const char *value) ;

/*
 Remove an inline style property from `node`. Thread-safe.
 */
 LumenStatus lumen_node_remove_style(LumenNode node, const char *name) ;

/*
 Create a fresh detached element with markup tag `tag`, writing its handle
 to `*out`. The handle is valid for the rest of the tick; attach it with
 [`lumen_node_append`] / [`lumen_node_set_parent`]. Thread-safe.
 */
 LumenStatus lumen_node_spawn(const char *tag, LumenNode *out) ;

/*
 Deep-clone `source`'s subtree into a fresh detached node, writing its
 handle to `*out`. Thread-safe.
 */
 LumenStatus lumen_node_clone(LumenNode source, LumenNode *out) ;

/*
 Append `child` under `parent` (`appendChild`). Thread-safe.
 */
 LumenStatus lumen_node_append(LumenNode parent, LumenNode child) ;

/*
 Insert `child` under `parent` before `reference` (`insertBefore`).
 A `reference` of `0` appends. Thread-safe.
 */
 LumenStatus lumen_node_insert_before(LumenNode parent, LumenNode child, LumenNode reference) ;

/*
 Attach `node` under `parent` (`node.set_parent` / reparent). Thread-safe.
 */
 LumenStatus lumen_node_set_parent(LumenNode node, LumenNode parent) ;

/*
 Replace `old` with `new` in `old`'s parent, despawning `old`'s subtree.
 Thread-safe.
 */
 LumenStatus lumen_node_replace_with(LumenNode old, LumenNode new_) ;

/*
 Detach and despawn `node` and its subtree (`node.remove`). Thread-safe.
 */
 LumenStatus lumen_node_remove(LumenNode node) ;

/*
 `window.set_href`: navigate to a page path. Binds onto the same
 [`lumen_core::nav`] bus as [`lumen_navigate`]. Thread-safe.
 */
 LumenStatus lumen_window_set_href(const char *path) ;

/*
 `window.reload`: re-navigate to the current page. Thread-safe.
 */
 LumenStatus lumen_window_reload(void) ;

/*
 `window.set_title`. Thread-safe.
 */
 LumenStatus lumen_window_set_title(const char *title) ;

/*
 `window.set_size` in logical pixels. Thread-safe.
 */
 LumenStatus lumen_window_set_size(float width, float height) ;

/*
 `window.dpr`: current device-pixel ratio, written to `*out`.
 Thread-safe.
 */
 LumenStatus lumen_window_dpr(float *out) ;

/*
 `history.go(delta)`: step `delta` entries (negative back, positive
 forward) through the in-memory history stack. Thread-safe.
 */
 LumenStatus lumen_history_go(int delta) ;

/*
 `document.spawn(tag)`: document-scoped create verb; writes the new
 handle to `*out`. Thread-safe.
 */
 LumenStatus lumen_document_spawn(const char *tag, LumenNode *out) ;

/*
 Unbind a callback previously registered with [`lumen_on`]. No-op for an
 unknown token. Thread-safe.
 */
 LumenStatus lumen_off(LumenEventToken token) ;

/*
 Copy the current event's type name into `buf` (string-out convention:
 `*out_len` excludes the NUL; too-small returns
 [`LumenStatus::ErrBufferTooSmall`] with the required capacity). Valid only
 inside a [`LumenEventFn`] callback. Thread-safe.
 */
 LumenStatus lumen_event_type(char *buf, size_t buf_len, size_t *out_len) ;

/*
 Copy the current event's `key` (keyboard events) into `buf`. See
 [`lumen_event_type`] for the convention. Thread-safe.
 */
 LumenStatus lumen_event_key(char *buf, size_t buf_len, size_t *out_len) ;

/*
 Copy the current event's `value` (input / change events) into `buf`. See
 [`lumen_event_type`] for the convention. Thread-safe.
 */
 LumenStatus lumen_event_value(char *buf, size_t buf_len, size_t *out_len) ;

/*
 The current event's target node (packed handle), or `0` outside a
 callback. Thread-safe.
 */
 LumenNode lumen_event_target(void) ;

/*
 The current event's `current_target` node (packed handle). Thread-safe.
 */
 LumenNode lumen_event_current_target(void) ;

/*
 Cancel the current event's default action (link navigation for `click`,
 form submission for `submit`). Thread-safe.
 */
 LumenStatus lumen_event_prevent_default(void) ;

/*
 Stop the current event propagating to further nodes. Thread-safe.
 */
 LumenStatus lumen_event_stop_propagation(void) ;

/*
 Stop the current event immediately: no further handlers run, on this node
 or any other. Thread-safe.
 */
 LumenStatus lumen_event_stop_immediate_propagation(void) ;

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LUMEN_SIMPLE_H */
