//! Test-only compiler plugin. Every behavior is driven by the entry's
//! `config` table in `lumen.toml`, so one build of this cdylib covers the
//! happy path of all five hooks and every failure mode:
//!
//! - `order`: appended before the literal `/END` in the markup, so several
//!   entries of this same library prove declaration-order chaining.
//! - markup: `FROM_PLUGIN_MARKUP` becomes `markup-transformed`.
//! - CSS: `PLUGIN_COLOR` becomes `rgb(255, 0, 0)`.
//! - `inject_text`: a `<label class="from-plugin">` child appended to the
//!   root, which the cascade must then style like hand-written markup.
//! - `lint_message`: emitted as an info finding anchored at 1:1.
//! - `emit_path`: one generated file holding `generated by fixture`.
//! - `synthesize_css`: returned as the whole stylesheet when the app ships
//!   none (the hook sees the empty string).
//! - `invalid_markup`: the markup hook returns text that is not XML.
//! - `wrong_root`: the markup hook returns well-formed XML the markup
//!   parser rejects, so the failure lands past the include resolver.
//! - `fail` / `panic_in`: name a hook (`markup`, `css`, `ir`, `lint`,
//!   `emit`) to make it error or panic.
//! - env `LUMEN_FIXTURE_CTOR_PANIC`: the constructor itself panics, for the
//!   first-call-construction failure path.

use lumenc_plugin::{
    CompilerPlugin, Ctx, Error, Finding, LayoutIR, Output, Severity, lumenc_plugin,
};
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
struct Cfg {
    order: Option<String>,
    inject_text: Option<String>,
    lint_message: Option<String>,
    emit_path: Option<String>,
    emit_bad_path: Option<String>,
    synthesize_css: Option<String>,
    invalid_markup: bool,
    wrong_root: bool,
    fail: Option<String>,
    panic_in: Option<String>,
}

impl Cfg {
    fn gate(&self, hook: &str) -> Result<(), Error> {
        if self.panic_in.as_deref() == Some(hook) {
            panic!("fixture panic in {hook}");
        }
        if self.fail.as_deref() == Some(hook) {
            return Err(Error::from(format!("fixture failure in {hook}")));
        }
        Ok(())
    }
}

struct FixturePlugin;

impl FixturePlugin {
    fn new() -> Self {
        if std::env::var_os("LUMEN_FIXTURE_CTOR_PANIC").is_some() {
            panic!("fixture panic in constructor");
        }
        FixturePlugin
    }
}

impl CompilerPlugin for FixturePlugin {
    fn transform_markup(&self, src: &str, ctx: &Ctx) -> Result<Option<String>, Error> {
        let cfg: Cfg = ctx.config()?;
        cfg.gate("markup")?;
        if cfg.invalid_markup {
            return Ok(Some("<root><label></root>".to_string()));
        }
        if cfg.wrong_root {
            return Ok(Some("<notroot/>".to_string()));
        }
        let mut out = src.to_string();
        let mut changed = false;
        if let Some(order) = &cfg.order {
            out = out.replace("/END", &format!("{order}/END"));
            changed = true;
        }
        if out.contains("FROM_PLUGIN_MARKUP") {
            out = out.replace("FROM_PLUGIN_MARKUP", "markup-transformed");
            changed = true;
        }
        Ok(changed.then_some(out))
    }

    fn transform_css(&self, src: &str, ctx: &Ctx) -> Result<Option<String>, Error> {
        let cfg: Cfg = ctx.config()?;
        cfg.gate("css")?;
        if let (true, Some(sheet)) = (src.is_empty(), cfg.synthesize_css) {
            return Ok(Some(sheet));
        }
        Ok(src
            .contains("PLUGIN_COLOR")
            .then(|| src.replace("PLUGIN_COLOR", "rgb(255, 0, 0)")))
    }

    fn transform_ir(&self, ir: &mut LayoutIR, ctx: &Ctx) -> Result<(), Error> {
        let cfg: Cfg = ctx.config()?;
        cfg.gate("ir")?;
        if let Some(text) = cfg.inject_text {
            let mut child = lumenc_plugin::lumen_ir::layout_ir::Element {
                tag: "label".to_string(),
                ..Default::default()
            };
            child.attrs.text = Some(text);
            child.attrs.classes = vec!["from-plugin".to_string()];
            ir.root.children.push(child);
        }
        Ok(())
    }

    fn lint(&self, _ir: &LayoutIR, ctx: &Ctx) -> Result<Vec<Finding>, Error> {
        let cfg: Cfg = ctx.config()?;
        cfg.gate("lint")?;
        let Some(message) = cfg.lint_message else {
            return Ok(Vec::new());
        };
        Ok(vec![Finding {
            rule: "fixture".to_string(),
            severity: Severity::Info,
            message,
            file: None,
            line: 1,
            col: 1,
            suggest: None,
        }])
    }

    fn emit(&self, _ir: &LayoutIR, ctx: &Ctx) -> Result<Vec<Output>, Error> {
        let cfg: Cfg = ctx.config()?;
        cfg.gate("emit")?;
        let mut outputs = Vec::new();
        if let Some(path) = cfg.emit_path {
            outputs.push(Output {
                path,
                bytes: b"generated by fixture".to_vec(),
            });
        }
        if let Some(path) = cfg.emit_bad_path {
            outputs.push(Output {
                path,
                bytes: Vec::new(),
            });
        }
        Ok(outputs)
    }
}

lumenc_plugin!(FixturePlugin::new);
