[package]
name = "lumen-render-headless"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "In-memory RGBA renderer for CI and tests."
keywords = ["ui", "gui", "rendering", "headless", "testing"]
categories = ["rendering", "gui"]

[dependencies]
lumen-core = { path = "../../core", version = "0.0.3" }
lumen-text = { path = "../../text", version = "0.0.3" }
bevy_ecs.workspace = true
glam.workspace = true

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
lumen-layout-taffy = { path = "../layout-taffy" }
glam.workspace = true
