/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_SLASH_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_script = 5,
  sym_raw_text = 6,
  sym_tag_name = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  anon_sym_DQUOTE = 10,
  anon_sym_SQUOTE = 11,
  sym__attribute_text_double = 12,
  sym__attribute_text_single = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  sym_signal_reference = 16,
  sym_row_reference = 17,
  sym_identifier = 18,
  sym_interpolation_text = 19,
  sym_entity = 20,
  sym_text = 21,
  sym_processing_instruction = 22,
  sym_comment = 23,
  sym_document = 24,
  sym__node = 25,
  sym_element = 26,
  sym_start_tag = 27,
  sym_self_closing_tag = 28,
  sym_end_tag = 29,
  sym_script_element = 30,
  sym_script_start_tag = 31,
  sym_script_self_closing_tag = 32,
  sym_script_end_tag = 33,
  sym__script_tag_name = 34,
  sym_attribute = 35,
  sym_quoted_attribute_value = 36,
  sym_interpolation = 37,
  aux_sym_document_repeat1 = 38,
  aux_sym_start_tag_repeat1 = 39,
  aux_sym_quoted_attribute_value_repeat1 = 40,
  aux_sym_quoted_attribute_value_repeat2 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_script] = "script",
  [sym_raw_text] = "raw_text",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym__attribute_text_double] = "attribute_value",
  [sym__attribute_text_single] = "attribute_value",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_signal_reference] = "signal_reference",
  [sym_row_reference] = "row_reference",
  [sym_identifier] = "identifier",
  [sym_interpolation_text] = "interpolation_text",
  [sym_entity] = "entity",
  [sym_text] = "text",
  [sym_processing_instruction] = "processing_instruction",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_script_element] = "script_element",
  [sym_script_start_tag] = "start_tag",
  [sym_script_self_closing_tag] = "self_closing_tag",
  [sym_script_end_tag] = "end_tag",
  [sym__script_tag_name] = "tag_name",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_interpolation] = "interpolation",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_quoted_attribute_value_repeat1] = "quoted_attribute_value_repeat1",
  [aux_sym_quoted_attribute_value_repeat2] = "quoted_attribute_value_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_script] = anon_sym_script,
  [sym_raw_text] = sym_raw_text,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym__attribute_text_double] = sym__attribute_text_double,
  [sym__attribute_text_single] = sym__attribute_text_double,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_signal_reference] = sym_signal_reference,
  [sym_row_reference] = sym_row_reference,
  [sym_identifier] = sym_identifier,
  [sym_interpolation_text] = sym_interpolation_text,
  [sym_entity] = sym_entity,
  [sym_text] = sym_text,
  [sym_processing_instruction] = sym_processing_instruction,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_script_element] = sym_script_element,
  [sym_script_start_tag] = sym_start_tag,
  [sym_script_self_closing_tag] = sym_self_closing_tag,
  [sym_script_end_tag] = sym_end_tag,
  [sym__script_tag_name] = sym_tag_name,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_quoted_attribute_value_repeat1] = aux_sym_quoted_attribute_value_repeat1,
  [aux_sym_quoted_attribute_value_repeat2] = aux_sym_quoted_attribute_value_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_script] = {
    .visible = true,
    .named = false,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__attribute_text_double] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_text_single] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_signal_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_row_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation_text] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_processing_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__script_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 31,
  [36] = 31,
  [37] = 37,
  [38] = 7,
  [39] = 14,
  [40] = 18,
  [41] = 7,
  [42] = 14,
  [43] = 18,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 51,
  [56] = 56,
  [57] = 51,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 62,
  [65] = 61,
  [66] = 62,
  [67] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '"', 53,
        '$', 25,
        '&', 6,
        '\'', 54,
        '/', 19,
        '<', 28,
        '=', 51,
        '>', 29,
        'r', 38,
        's', 36,
        '{', 71,
        '}', 72,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '$') ADVANCE(88);
      if (lookahead == '<') ADVANCE(82);
      if (lookahead == 'r') ADVANCE(76);
      if (lookahead == '}') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(89);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '<') ADVANCE(82);
      if (lookahead == '}') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(89);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(9);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '&') ADVANCE(6);
      if (lookahead == '<') ADVANCE(55);
      if (lookahead == '{') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '&') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '<') ADVANCE(63);
      if (lookahead == '{') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(21);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(10);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '=') ADVANCE(51);
      if (lookahead == '>') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'') ADVANCE(52);
      END_STATE();
    case 13:
      if (lookahead == ';') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == ';') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == ';') ADVANCE(90);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == 's') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == '<') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == '<') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == '>') ADVANCE(92);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(93);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 22:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 23:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(91);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 25:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '&') ADVANCE(6);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '{') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(91);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(9);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '?') ADVANCE(20);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_script);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_raw_text);
      if (lookahead == '<') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_raw_text);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == 'i') ADVANCE(39);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == 'o') ADVANCE(42);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == 'p') ADVANCE(41);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(37);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == 'w') ADVANCE(35);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(48);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(47);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'p') ADVANCE(49);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead == '!') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead == '-') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead == '-') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead == '<') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead == '>') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__attribute_text_double);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead == '!') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead == '-') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead == '-') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead == '<') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead == '>') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(66);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__attribute_text_single);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_signal_reference);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_row_reference);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(77);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(75);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '$') ADVANCE(88);
      if (lookahead == '<') ADVANCE(82);
      if (lookahead == 'r') ADVANCE(76);
      if (lookahead == '}') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(89);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '<') ADVANCE(82);
      if (lookahead == '}') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(89);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '!') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '-') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '-') ADVANCE(87);
      if (lookahead == '\n' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '-') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '-') ADVANCE(84);
      if (lookahead == '\n' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead == '>') ADVANCE(93);
      if (lookahead == '\n' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_interpolation_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_processing_instruction);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 26},
  [2] = {.lex_state = 26},
  [3] = {.lex_state = 26},
  [4] = {.lex_state = 26},
  [5] = {.lex_state = 26},
  [6] = {.lex_state = 26},
  [7] = {.lex_state = 26},
  [8] = {.lex_state = 26},
  [9] = {.lex_state = 26},
  [10] = {.lex_state = 26},
  [11] = {.lex_state = 26},
  [12] = {.lex_state = 26},
  [13] = {.lex_state = 26},
  [14] = {.lex_state = 26},
  [15] = {.lex_state = 26},
  [16] = {.lex_state = 26},
  [17] = {.lex_state = 26},
  [18] = {.lex_state = 26},
  [19] = {.lex_state = 26},
  [20] = {.lex_state = 26},
  [21] = {.lex_state = 26},
  [22] = {.lex_state = 26},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 12},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 12},
  [50] = {.lex_state = 18},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 18},
  [53] = {.lex_state = 18},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 17},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_script] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_signal_reference] = ACTIONS(1),
    [sym_row_reference] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [sym_processing_instruction] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(60),
    [sym__node] = STATE(5),
    [sym_element] = STATE(5),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_tag] = STATE(11),
    [sym_script_element] = STATE(11),
    [sym_script_start_tag] = STATE(50),
    [sym_script_self_closing_tag] = STATE(9),
    [sym_interpolation] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_entity] = ACTIONS(11),
    [sym_text] = ACTIONS(11),
    [sym_processing_instruction] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(8), 1,
      sym_end_tag,
    STATE(9), 1,
      sym_script_self_closing_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(11), 2,
      sym_self_closing_tag,
      sym_script_element,
    ACTIONS(15), 3,
      sym_entity,
      sym_text,
      sym_processing_instruction,
    STATE(3), 4,
      sym__node,
      sym_element,
      sym_interpolation,
      aux_sym_document_repeat1,
  [40] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(6), 1,
      sym_end_tag,
    STATE(9), 1,
      sym_script_self_closing_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(11), 2,
      sym_self_closing_tag,
      sym_script_element,
    ACTIONS(17), 3,
      sym_entity,
      sym_text,
      sym_processing_instruction,
    STATE(4), 4,
      sym__node,
      sym_element,
      sym_interpolation,
      aux_sym_document_repeat1,
  [80] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(24), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym_start_tag,
    STATE(9), 1,
      sym_script_self_closing_tag,
    STATE(50), 1,
      sym_script_start_tag,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
    STATE(11), 2,
      sym_self_closing_tag,
      sym_script_element,
    ACTIONS(27), 3,
      sym_entity,
      sym_text,
      sym_processing_instruction,
    STATE(4), 4,
      sym__node,
      sym_element,
      sym_interpolation,
      aux_sym_document_repeat1,
  [118] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(9), 1,
      sym_script_self_closing_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(11), 2,
      sym_self_closing_tag,
      sym_script_element,
    ACTIONS(17), 3,
      sym_entity,
      sym_text,
      sym_processing_instruction,
    STATE(4), 4,
      sym__node,
      sym_element,
      sym_interpolation,
      aux_sym_document_repeat1,
  [155] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(32), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [170] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(36), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_LT,
    ACTIONS(40), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_LT,
    ACTIONS(44), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [215] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_LT,
    ACTIONS(48), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [230] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_LT,
    ACTIONS(52), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [245] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(56), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LT,
    ACTIONS(60), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [275] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_LT,
    ACTIONS(64), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [290] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LT,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [305] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [320] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LT,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [335] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(80), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [350] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LT,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LT,
    ACTIONS(88), 6,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [380] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_LT,
    ACTIONS(94), 5,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_LT,
    ACTIONS(98), 5,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_entity,
      sym_text,
      sym_processing_instruction,
  [408] = 6,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    ACTIONS(102), 1,
      sym__attribute_text_double,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 1,
      sym_entity,
    ACTIONS(108), 1,
      sym_comment,
    STATE(25), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [428] = 6,
    ACTIONS(100), 1,
      anon_sym_SQUOTE,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__attribute_text_single,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      sym_entity,
    STATE(26), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [448] = 6,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym__attribute_text_double,
    ACTIONS(120), 1,
      sym_entity,
    STATE(27), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [468] = 6,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SQUOTE,
    ACTIONS(122), 1,
      sym__attribute_text_single,
    ACTIONS(124), 1,
      sym_entity,
    STATE(28), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [488] = 6,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_DQUOTE,
    ACTIONS(128), 1,
      sym__attribute_text_double,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
    ACTIONS(134), 1,
      sym_entity,
    STATE(27), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [508] = 6,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      sym__attribute_text_single,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    ACTIONS(145), 1,
      sym_entity,
    STATE(28), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [528] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_GT,
    ACTIONS(150), 1,
      anon_sym_SLASH_GT,
    ACTIONS(152), 1,
      sym_attribute_name,
    STATE(33), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [545] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_attribute_name,
    ACTIONS(154), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(30), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [560] = 4,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(163), 1,
      sym_interpolation_text,
    ACTIONS(161), 3,
      sym_signal_reference,
      sym_row_reference,
      sym_identifier,
  [575] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_attribute_name,
    ACTIONS(165), 1,
      anon_sym_GT,
    ACTIONS(167), 1,
      anon_sym_SLASH_GT,
    STATE(34), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [592] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_attribute_name,
    ACTIONS(169), 1,
      anon_sym_GT,
    ACTIONS(171), 1,
      anon_sym_SLASH_GT,
    STATE(30), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [609] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_attribute_name,
    ACTIONS(173), 1,
      anon_sym_GT,
    ACTIONS(175), 1,
      anon_sym_SLASH_GT,
    STATE(30), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [626] = 4,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(181), 1,
      sym_interpolation_text,
    ACTIONS(179), 3,
      sym_signal_reference,
      sym_row_reference,
      sym_identifier,
  [641] = 4,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(187), 1,
      sym_interpolation_text,
    ACTIONS(185), 3,
      sym_signal_reference,
      sym_row_reference,
      sym_identifier,
  [656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_EQ,
    ACTIONS(189), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [668] = 3,
    ACTIONS(36), 1,
      sym__attribute_text_double,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(38), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_entity,
  [680] = 3,
    ACTIONS(64), 1,
      sym__attribute_text_double,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(66), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_entity,
  [692] = 3,
    ACTIONS(80), 1,
      sym__attribute_text_double,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_entity,
  [704] = 3,
    ACTIONS(36), 1,
      sym__attribute_text_single,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(38), 3,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      sym_entity,
  [716] = 3,
    ACTIONS(64), 1,
      sym__attribute_text_single,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(66), 3,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      sym_entity,
  [728] = 3,
    ACTIONS(80), 1,
      sym__attribute_text_single,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      sym_entity,
  [740] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_DQUOTE,
    ACTIONS(195), 1,
      anon_sym_SQUOTE,
    STATE(47), 1,
      sym_quoted_attribute_value,
  [753] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [762] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_script,
    ACTIONS(201), 1,
      sym_tag_name,
    STATE(29), 1,
      sym__script_tag_name,
  [775] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [793] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [802] = 4,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_LT_SLASH,
    ACTIONS(211), 1,
      sym_raw_text,
    STATE(10), 1,
      sym_script_end_tag,
  [815] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    ACTIONS(215), 1,
      sym_interpolation_text,
  [825] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_LT_SLASH,
      sym_raw_text,
  [833] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(219), 2,
      anon_sym_LT_SLASH,
      sym_raw_text,
  [841] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_script,
    STATE(59), 1,
      sym__script_tag_name,
  [851] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    ACTIONS(223), 1,
      sym_interpolation_text,
  [861] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LT_SLASH,
    STATE(15), 1,
      sym_script_end_tag,
  [871] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    ACTIONS(229), 1,
      sym_interpolation_text,
  [881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_GT,
  [888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_GT,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [902] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_tag_name,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 118,
  [SMALL_STATE(6)] = 155,
  [SMALL_STATE(7)] = 170,
  [SMALL_STATE(8)] = 185,
  [SMALL_STATE(9)] = 200,
  [SMALL_STATE(10)] = 215,
  [SMALL_STATE(11)] = 230,
  [SMALL_STATE(12)] = 245,
  [SMALL_STATE(13)] = 260,
  [SMALL_STATE(14)] = 275,
  [SMALL_STATE(15)] = 290,
  [SMALL_STATE(16)] = 305,
  [SMALL_STATE(17)] = 320,
  [SMALL_STATE(18)] = 335,
  [SMALL_STATE(19)] = 350,
  [SMALL_STATE(20)] = 365,
  [SMALL_STATE(21)] = 380,
  [SMALL_STATE(22)] = 394,
  [SMALL_STATE(23)] = 408,
  [SMALL_STATE(24)] = 428,
  [SMALL_STATE(25)] = 448,
  [SMALL_STATE(26)] = 468,
  [SMALL_STATE(27)] = 488,
  [SMALL_STATE(28)] = 508,
  [SMALL_STATE(29)] = 528,
  [SMALL_STATE(30)] = 545,
  [SMALL_STATE(31)] = 560,
  [SMALL_STATE(32)] = 575,
  [SMALL_STATE(33)] = 592,
  [SMALL_STATE(34)] = 609,
  [SMALL_STATE(35)] = 626,
  [SMALL_STATE(36)] = 641,
  [SMALL_STATE(37)] = 656,
  [SMALL_STATE(38)] = 668,
  [SMALL_STATE(39)] = 680,
  [SMALL_STATE(40)] = 692,
  [SMALL_STATE(41)] = 704,
  [SMALL_STATE(42)] = 716,
  [SMALL_STATE(43)] = 728,
  [SMALL_STATE(44)] = 740,
  [SMALL_STATE(45)] = 753,
  [SMALL_STATE(46)] = 762,
  [SMALL_STATE(47)] = 775,
  [SMALL_STATE(48)] = 784,
  [SMALL_STATE(49)] = 793,
  [SMALL_STATE(50)] = 802,
  [SMALL_STATE(51)] = 815,
  [SMALL_STATE(52)] = 825,
  [SMALL_STATE(53)] = 833,
  [SMALL_STATE(54)] = 841,
  [SMALL_STATE(55)] = 851,
  [SMALL_STATE(56)] = 861,
  [SMALL_STATE(57)] = 871,
  [SMALL_STATE(58)] = 881,
  [SMALL_STATE(59)] = 888,
  [SMALL_STATE(60)] = 895,
  [SMALL_STATE(61)] = 902,
  [SMALL_STATE(62)] = 909,
  [SMALL_STATE(63)] = 916,
  [SMALL_STATE(64)] = 923,
  [SMALL_STATE(65)] = 930,
  [SMALL_STATE(66)] = 937,
  [SMALL_STATE(67)] = 944,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_self_closing_tag, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_self_closing_tag, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_self_closing_tag, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_self_closing_tag, 4, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_end_tag, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_end_tag, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(36),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__script_tag_name, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lumen(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
